/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#F9FAFB',
        border: '#D1D5DB',
        'border-two': '#BFDBFE',
        primary: '#3B82F6',
        'text-one': '#1F2937',
        'text-two': '#ADAEBC',
        'text-three': '#4B5563',
        'text-four': '#DBEAFE',
        'text-five': '#6B7280',
        'text-six': '#374151',
        'primary-light': '#EFF6FF',
        'status-success': '#10B981',
        'status-success-bg': '#D1FAE5',
        'status-success-text': '#065F46',
        'status-warning': '#F59E0B',
        'status-warning-bg': '#FEF3C7',
        'status-warning-text': '#92400E',
        'status-danger': '#EF4444',
        'status-danger-bg': '#FEE2E2',
        'status-danger-text': '#991B1B',
        'status-waiting': '#9CA3AF',
        'status-waiting-bg': '#F3F4F6',
        'status-waiting-text': '#374151',
      },
      fontFamily: {
        inter: 'Inter_Regular',
        'inter-medium': 'Inter_Medium',
        'inter-bold': 'Inter_Bold',
        'inter-semibold': 'Inter_SemiBold',
      },
    },
  },
  plugins: [],
}
