export const autors = [
  'Renata Andrea Salvitti de Sá Rocha - Professora de Odontopediatria e Psicologia Aplicada a Odontologia da Universidade Federal de Campina Grande',
  'Catarina Ribeiro Barros de Alencar - Professora Visitante da Universidade Federal de Campina Grande',
  'Maria Luísa de Assis Braga - Acadêmica de Odontologia da Universidade Federal de Campina Grande',
  'Andressa Nascimento de Souza - Cirurgiã-dentista',
  'João Pedrosa Wanderley Neto - Fotógrafo; Acadêmico de Odontologia da Universidade Federal de Campina Grande',
]

export const references = [
  '1. Caldana RHL, ALVES ZMMB. Psicologia do desenvolvimento: contribuições à odontopediatria. Rev Odontol Univ São Paulo. 1990; 4(3): 260-265.',
  '2. Torriane DD. Análise do comportamento de bebês durante atendimento odontológico: relação entre sexo, idade e dentes irrompidos [dissertação]. Araçatuba: Universidade Estadual Paulista; 1999.',
  '3. Milgrom P, Weistein P, Getz T. Treating fearful dental patients. Washington: University of Washington in Seattle; 1995.',
  '4. Singh KA, Moraes ABA, Bovi Ambrosano, GM. Medo, ansiedade e controle relacionados ao tratamento odontológico. Pesq Odont Bras. 2000; 14(2): 131-136.',
  '5. Moraes ABA, Rolim GS. Psicologia da saúde em odontologia: saúde e comportamento. 1.ed. Curitiba: Juruá; 2017.',
  '6. American Academy of Pediatric Dentistry. Guideline on Behavior Guidance for the Pediatric Dental Patient. Pediatr Dent; 2015.',
  '7. Moraes ABA, Pessotti I. Psicologia Aplicada à Odontologia. Campinas: Ed. da Universidade Estadual de Campinas; 1985.',
  '8. Weinstein P, Nathan JE. The challenge of fearful and phobic children. Dental Clinics Of North America. 1988 jan: 667-692.',
  '9. Costa Junior AL. Psicologia Aplicada à Odontopediatria: Uma Introdução. Public Knowledge Project. 2002: 1-8.',
  '10. Wright GZ, Kupietzky A. Behavior management in dentistry for children. New Hersey: Wiley Blackwell, 2014.',
  '11. Rocha RASS, Rolim GS, Moraes ABA. Inclusão de Crianças na Escolha de Estratégias de Manejo Comportamental em Odontopediatria: Saúde & Transformação Social / Health & Social Change. 6. ed. Santa Catarina: Universidade Federal de Santa Catarina, 2015.',
  '12. Josgrilberg EB, Cordeiro RCL. Aspectos psicológicos do paciente infantil no atendimento de urgência. Odontol Clin Cient. 2005; 4(1): 13-7.',
  '13. Barenie JT, Ripa LW. The use of behavior modification techniques to successfully manage the child dental patient. JADA. 1997 fev; 94(2): 329-334.',
  '14. Klatchoian DA, Toledo AO. Aspectos Psicológicos na clínica odontopediátrica. In: Toledo AO. Odontopediatria. Fundamentos para a prática clínica. 3. ed. São Paulo: Editoral Premier; 2005.',
  '15. Leite DFBM, Muniz IAF, Farias IAP. Condução psicológica do paciente infantil em Saúde Pública. Rev Odonto. 2013; 12(4): 251-254.',
  '16. Martin G, Pear JJ. Behavior modification: what is and now to do it. 10.ed. New York: Psychology Press; 2015.',
  '17. Roberts JF, Curzon MEJ, Koch G, Martens LC. Behaviour management techniques in paediatric dentistry. Europen Archives Of Paediatric Dentistry. 2010 ago; 11(4): 166–174.',
  '18. Oliveira AVM. O uso das novas tecnologias de informação e comunicação (NTIC) para o ensino continuado da disciplina de odontopediatria [dissertação]. Florianópolis: Universidade Federal de Santa Catarina; 2002.',
  '19. Bausells J. Odontopediatria procedimentos clínicos. In: Zuanon ACC, Hebling J, Bausells J. Medidas preventivas. São Paulo: Premier; 1997.',
  '20. Rocha RASS. Manejo de comportamentos em odontopediatria: análise de escolhas da criança [tese]. Piracicaba: Universidade Estadual de Campinas, Faculdade de Odontologia de Piracicaba; 2010.',
  '21. Kuhn BR, Allen KD. Expanding child behaviour technology in pediatric dentistry: a behavioural science perspective. Pediatr Dent. 1994 fev; 16(1): 13-17.',
  '22. Possobon RF. Uso combinado de estratégias comportamentais e farmacológicas no manejo da criança não-colaboradora durante o atendimento odontológico [dissertação]. Piracicaba: Universidade Estadual de Campinas, Faculdade de Odontologia de Piracicaba; 2000.',
  '23. Moore MMA, Russ SW. Pretend play as a resource for children: implications for pediatricians and health professionals. Journal of Developmental & Behavioral Pediatrics. 2006 jun; 27(3): 237-248.',
  '24. Mitre RMA, Gomes RA. Promoção do brincar no contexto da hospitalização infantil como ação de saúde. Ciência & Saúde Coletiva. 2004; 9(1): 147-154.',
  '25. Barreto RA, Cardoso MA, Corrêa MSNP. Humanização do Atendimento Odontopediátrico: A Arte de uma Renovação. In: Corrêa, Maria Salete Nahás Pires. Conduta clínica e psicológica na odontopediatria. 2. Ed. São Paulo: Livraria Santos e Editora; 2013.',
  '26. Cota ALS, Costa BJA. Atividades lúdicas como estratégia para a promoção da saúde bucal infantil. Rev Saúde e Pesquisa. 2017; 10(2): 365-371.',
  '27. Mialhe FL, Cunha RGOB, Júnior MM. Avaliação dos jogos e brinquedos com temas odontológicos disponibilizados no mercado nacional. Pesquisa Brasileira Odontopediátrica Clínica Integrada. 2009; 9(3): 303-308.',
  '28. Oliveira JCC. Atividades lúdicas na Odontopediatria: uma breve revisão da literatura. Rev bras odontol. 2014; 71(1): 103-107.',
  '29. Pinkhan JR, Casamassino PS, Fields JR, Henry W. Odontopediatria da infância à adolescência. 2 ed. São Paulo: Editora Artes Médicas, 1996.',
  '30. Albuquerque CM, Gouvêa, CVD, Moraes RCM, Barros RN, Couto CF. Principais técnicas de controle de comportamento em Odontopediatria. Rev Odonto. 2010; 45(2): 110-115.',
  '31. Cardoso CL. Tratamento odontopediátrico no contexto de uma clínica-escola: avaliação do estresse da criança, do acompanhante e do aluno [tese]. Ribeirão Preto: Universidade de São Paulo; 2002.',
  '32. Kulich KR, Rydén O, Bengtsson H. A descriptive study of how dentists view their profession and the doctor patient relationship. Acta Odontol Scand. 1998; 56(1):  206-209.',
  '33. Yoshida T, Milgrom P, Coldwell S. How do U.S. and Canadian dental schools teach interpersonal communication skills? J Dent Educ. 2002; 66(11): 1281-1288.',
  '34. Hottel TL, Hardigan PC. Improvement in the interpersonal communication skills of dental students. J Dent Educ. 2005; 69(2): 281-284.',
  '35. Boynton JR, Johnson LA, Hashim SMN, Hu JCC. Portable digital video Instruction in Predoctoral Education of child behavior management. J Dent Educ. 2007; 71(4): 545-549 (a).',
  '36. Boynton JR, Green TG, Johnson LA, Hashim SMN, Straffon LH. The Virtual Child: evaluation of an internet-based pediatric behavior management simulation. J Dent Educ. 2007; 71(9): 1187-1193 (b)',
  '37. Gage, NL; Berliner, DC. Educational Psychology, 3 ed. Boston:Houghton Mifflin, 1984.',
]
